spring.application.name=jpa-app

port=8081

#  Conexión a PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/protienda
spring.datasource.username=admin
spring.datasource.password=admin123
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Show best formated SQL logs
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true
spring.jpa.properties.hibernate.generate_statistics=true



#  Configuración de HikariCP (pool de conexiones)
# Máximo de conexiones en el pool
spring.datasource.hikari.maximum-pool-size=20
# Conexiones mínimas en reposo
spring.datasource.hikari.minimum-idle=5
# Tiempo máx. de inactividad (ms)
spring.datasource.hikari.idle-timeout=30000
# Tiempo máx. de espera para obtener conexión (ms)
spring.datasource.hikari.connection-timeout=20000
# Tiempo de vida máx. de una conexión (ms)
spring.datasource.hikari.max-lifetime=1800000

